apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  releaseName: sonarqube
  interval: 10m
  chart:
    spec:
      chart: sonarqube
      version: "2025.3.0"
      sourceRef:
        kind: HelmRepository
        name: sonarqube-repo
        namespace: flux-system
  values:
    ingress:
      enabled: true
      hosts:
        - name: sonarqube.local
          path: /
      annotations: {}
      tls:
        - secretName: sonarqube-tls
          hosts:
            - sonarqube.local
    adminPassword: "123456"
    persistence:
      enabled: true
      storageClass: ""
      size: 10Gi
    service:
      type: ClusterIP
