apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/managed-by: fluxcd
    app.kubernetes.io/component: monitoring
    app: grafana
    release: kube-prometheus-stack

type: Opaque
data:
  admin-user: YWRtaW4=
  admin-password: cHJvbS1vcGVyYXRvcg==
