apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "48.3.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      # hardcodeamos aquí el usuario y la contraseña
      adminUser: "admin"
      adminPassword: "123456"
      # eliminamos cualquier referencia a Secret externo
      existingSecret: ""
      service:
        type: ClusterIP
      ingress:
        enabled: true
        hosts:
          - grafana.local
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.local

    prometheus:
      service:
        type: ClusterIP
      ingress:
        enabled: true
        hosts:
          - prometheus.local
        tls:
          - secretName: prometheus-tls
            hosts:
              - prometheus.local
