apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "48.3.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      enabled: true
      adminUser: "admin"
      adminPassword: "123456"
      existingSecret: ""
      service:
        type: ClusterIP
      ingress:
        enabled: true
        hosts:
          - grafana.local
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.local
      dashboards:
        default:
          k8s-cluster-resources:
            gnetId: 315
            revision: 4
            datasource: Prometheus
    prometheus:
      service:
        type: ClusterIP
      ingress:
        enabled: true
        hosts:
          - prometheus.local
        tls:
          - secretName: prometheus-tls
            hosts:
              - prometheus.local
      prometheusSpec:
        secrets:
          - prometheus-admin-secret
    kube-state-metrics:
      enabled: true
    nodeExporter:
      enabled: true
    prometheus-node-exporter:
      enabled: true
    prometheusOperator:
      prometheusConfigReloader:
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
    defaultRules:
      create: true
      rules:
        kubeSchedulerAlerting: true
        kubeSchedulerRecording: true
        kubeControllerManager: true
        kubelet: true
        kubeProxy: true
        etcd: true
        general: true
        k8s: true
        node: true
        prometheus: true
        alertmanager: true
        kubeApiserver: true
        kubePrometheusGeneral: true
        kubePrometheusNodeRecording: true
        kubernetesApps: true
        kubernetesResources: true
        kubernetesStorage: true
        kubernetesSystem: true
        network: true
        nodeExporterAlerting: true
        nodeExporterRecording: true
        prometheusOperator: true
