apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubeview
  namespace: monitoring
spec:
  releaseName: kubeview
  interval: 10m
  chart:
    spec:
      chart: kubeview
      version: "0.1.29"
      sourceRef:
        kind: HelmRepository
        name: kubeview
        namespace: flux-system
  values:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      hosts:
        - kubeview.local
      tls:
        - secretName: kubeview-tls
          hosts:
            - kubeview.local
    basicAuth:
      enabled: true
      username: admin
      password: 123456
