apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitoring
spec:
  releaseName: metrics-server
  interval: 10m
  chart:
    spec:
      chart: metrics-server
      version: "3.12.1"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  values:
    args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    service:
      type: ClusterIP
