apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: monitoring
spec:
  releaseName: sonarqube
  interval: 10m
  chart:
    spec:
      chart: sonarqube
      version: "10.5.0+691"
      sourceRef:
        kind: HelmRepository
        name: sonarqube
        namespace: flux-system
  values:
    ingress:
      enabled: true
      hosts:
        - sonarqube.local
      tls:
        - secretName: sonarqube-tls
          hosts:
            - sonarqube.local
    adminPassword: "123456"
    persistence:
      enabled: true
      storageClass: ""
      size: 10Gi
    service:
      type: ClusterIP
